# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
