# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='headshot'),
        ),
    ]
