# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_auto_20191121_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, storage='profile_pics', upload_to=''),
        ),
    ]
