# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_user_website'),
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_event', to='login_register.User'),
        ),
    ]
