# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(null=True, upload_to='event_pic'),
        ),
    ]
