# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_auto_20191121_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
