# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-24 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_auto_20191124_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_messaged',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='login_register.User'),
        ),
    ]
